# kinaseドメインのみでCPI予測

TRAIN_DATASET=kinase_chembl_domain
TEST_DATASET=kinase_chembl_domain_small_test
MODEL=model_8_2   #############################
GPU=1
MAX_LEN_SEQ=572

## processing
# kinase domainの切り出し
#python script/processing/domain_exract_kinase.py

# make dataset train/test
#sh script/run_py/build_dataset.sh $TRAIN_DATASET
#sh script/run_py/build_dataset_test.sh $TRAIN_DATASET $MAX_LEN_SEQ
#↑一緒に動かすとエラー!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


## train
#sh script/run_py/train_kinase_chembl.sh $TRAIN_DATASET $MODEL $GPU

##=======================================================
## test
POINT=1 # 何epochごとに可視化するか
TIME=500 # 可視化する回数
VIZ_METHOD=ig

# 自動 all
#SEQ_LIST=`find data/original/kinase_chembl -type d -maxdepth 1  | sed 's!^.*/!!'`

# seq_list指定
#SEQ_LIST="KAPCA_HUMAN LCK_HUMAN KP2K2_HUMAN CDK5_HUMAN MK10_HUMAN KPCL_HUMAN PLK1_HUMAN KPCT_HUMAN MK09_HUMAN KPCB_HUMAN GSK3B_HUMAN KPCA_HUMAN AKT1_HUMAN ABL1_HUMAN PDPK1_HUMAN EGFR_HUMAN IGF1R_HUMAN AURKA_HUMAN CDK1_HUMAN CDK2_HUMAN CHK1_HUMAN INSR_HUMAN KC1D_HUMAN VGFR1_HUMAN SRC_HUMAN VGFR2_HUMAN MK14_HUMAN KSYK_HUMAN"

# neg>100
#SEQ_LIST="KAPCA_HUMAN LCK_HUMAN CDK5_HUMAN KPCL_HUMAN KPCT_HUMAN KPCB_HUMAN GSK3B_HUMAN KPCA_HUMAN AKT1_HUMAN EGFR_HUMAN IGF1R_HUMAN AURKA_HUMAN CDK1_HUMAN CDK2_HUMAN VGFR1_HUMAN SRC_HUMAN VGFR2_HUMAN"

#SEQ_LIST="KAPCA_HUMAN LCK_HUMAN CDK5_HUMAN KPCL_HUMAN KPCT_HUMAN" # gpu=0 screen=0
#SEQ_LIST="KPCB_HUMAN GSK3B_HUMAN KPCA_HUMAN AKT1_HUMAN EGFR_HUMAN" # gpu=1 screen=1
#SEQ_LIST="IGF1R_HUMAN AURKA_HUMAN CDK1_HUMAN CDK2_HUMAN" # gpu=2 screen=2
#SEQ_LIST="VGFR2_HUMAN SRC_HUMAN VGFR1_HUMAN" # gpu=3 screen=5
#SEQ_LIST="EGFR_HUMAN SRC_HUMAN KPCI_HUMAN" # gpu1 new
#SEQ_LIST="CDK19_HUMAN ERBB2_HUMAN" # gpu2 new


# 可視化GOOD AURKA_HUMAN CDK2_HUMAN EGFR_HUMAN 気になる GSK3B_HUMAN KPCA_HUMAN
#SEQ_LIST="AURKA_HUMAN CDK2_HUMAN"


#SEQ_LIST="EGFR_HUMAN GSK3B_HUMAN KPCA_HUMAN"
#SEQ_LIST="CDK1_HUMAN LCK_HUMAN CDK2_HUMAN AURKA_HUMAN VGFR2_HUMAN"
#SEQ_LIST="SRC_HUMAN CDK5_HUMAN ERBB2_HUMAN KAPCA_HUMAN"
SEQ_LIST="KPCI_HUMAN KPCL_HUMAN KPCT_HUMAN"




for SEQ_NAME in $SEQ_LIST
do
echo $SEQ_NAME
sh script/run_py/test_kinase_chembl.sh $TRAIN_DATASET $TEST_DATASET $MODEL $GPU $POINT $TIME $VIZ_METHOD $SEQ_NAME
done
